### ISSUE TITLE
More buttons inside of alert

### ISSUE THREAD

**Issue by breakcoding** [kvandake/SCLAlertView-Xamarin#6]
There is a way to add another InteractiveActionButton on the alert or can custom the control?

**Comment by kvandake** [comment]
No, because only the OK and CANCEL buttons are attached to the message.
* [iOS](https://github.com/kvandake/InteractiveAlert-Xamarin/blob/master/InteractiveAlert/InteractiveAlert.iOS/InteractiveAlertsImpl.cs#L49)
* [Android](https://github.com/kvandake/InteractiveAlert-Xamarin/blob/master/InteractiveAlert/InteractiveAlert.Droid/Alerts/BaseInteractiveDialogFragment.cs#L41)
